version: '3'

networks:
  laravel:


services:
  app:
    build:
      context: ./docker/production
      dockerfile: nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/production/nginx/cert.pem:/etc/cert.pem
      - ./docker/production/nginx/key.pem:/etc/key.pem
    depends_on:
      - php
      - mysql
      - redis
      - node
    networks:
      - laravel

  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - .:/etc/nginx/
    build:
      context: ./docker/production/certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: compilations
      MYSQL_ROOT_PASSWORD: password
    networks:
      - laravel

  php:
    build:
      context: ./docker/production
      dockerfile: php-fpm/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel
  node:
    image: node:21-alpine
    build:
      context: ./docker/production
      dockerfile: node/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    restart: on-failure
    tty: true # keep running
    networks:
      - laravel

