version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./nginx.conf.d:/etc/nginx/conf.d/
        ports:
            - "80:80"
        container_name: nginx
    php:
        image: php:8.3-fpm
        volumes:
            - ./:/var/www

